//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region Métadonnées de relation EDM

[assembly: EdmRelationshipAttribute("asdomiModel", "FK_intervention_patient", "patient", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(AsdomiEF.patient), "intervention", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AsdomiEF.intervention), true)]
[assembly: EdmRelationshipAttribute("asdomiModel", "FK_intervention_salarie", "salarie", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AsdomiEF.salarie), "intervention", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AsdomiEF.intervention), true)]
[assembly: EdmRelationshipAttribute("asdomiModel", "FK_intervention_vehicule", "vehicule", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(AsdomiEF.vehicule), "intervention", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AsdomiEF.intervention), true)]

#endregion

namespace AsdomiEF
{
    #region Contextes
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    public partial class asdomiEntities : ObjectContext
    {
        #region Constructeurs
    
        /// <summary>
        /// Initialise un nouvel objet asdomiEntities à l'aide de la chaîne de connexion trouvée dans la section 'asdomiEntities' du fichier de configuration d'application.
        /// </summary>
        public asdomiEntities() : base("name=asdomiEntities", "asdomiEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet asdomiEntities.
        /// </summary>
        public asdomiEntities(string connectionString) : base(connectionString, "asdomiEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet asdomiEntities.
        /// </summary>
        public asdomiEntities(EntityConnection connection) : base(connection, "asdomiEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Méthodes partielles
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propriétés ObjectSet
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<intervention> intervention
        {
            get
            {
                if ((_intervention == null))
                {
                    _intervention = base.CreateObjectSet<intervention>("intervention");
                }
                return _intervention;
            }
        }
        private ObjectSet<intervention> _intervention;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<patient> patient
        {
            get
            {
                if ((_patient == null))
                {
                    _patient = base.CreateObjectSet<patient>("patient");
                }
                return _patient;
            }
        }
        private ObjectSet<patient> _patient;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<salarie> salarie
        {
            get
            {
                if ((_salarie == null))
                {
                    _salarie = base.CreateObjectSet<salarie>("salarie");
                }
                return _salarie;
            }
        }
        private ObjectSet<salarie> _salarie;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<vehicule> vehicule
        {
            get
            {
                if ((_vehicule == null))
                {
                    _vehicule = base.CreateObjectSet<vehicule>("vehicule");
                }
                return _vehicule;
            }
        }
        private ObjectSet<vehicule> _vehicule;

        #endregion
        #region Méthodes AddTo
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet intervention. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddTointervention(intervention intervention)
        {
            base.AddObject("intervention", intervention);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet patient. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddTopatient(patient patient)
        {
            base.AddObject("patient", patient);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet salarie. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddTosalarie(salarie salarie)
        {
            base.AddObject("salarie", salarie);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet vehicule. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddTovehicule(vehicule vehicule)
        {
            base.AddObject("vehicule", vehicule);
        }

        #endregion
    }
    

    #endregion
    
    #region Entités
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="asdomiModel", Name="intervention")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class intervention : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet intervention.
        /// </summary>
        /// <param name="numSalarie">Valeur initiale de la propriété numSalarie.</param>
        /// <param name="dateIntervention">Valeur initiale de la propriété dateIntervention.</param>
        /// <param name="heureDebut">Valeur initiale de la propriété heureDebut.</param>
        public static intervention Createintervention(global::System.Int32 numSalarie, global::System.DateTime dateIntervention, global::System.TimeSpan heureDebut)
        {
            intervention intervention = new intervention();
            intervention.numSalarie = numSalarie;
            intervention.dateIntervention = dateIntervention;
            intervention.heureDebut = heureDebut;
            return intervention;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 numSalarie
        {
            get
            {
                return _numSalarie;
            }
            set
            {
                if (_numSalarie != value)
                {
                    OnnumSalarieChanging(value);
                    ReportPropertyChanging("numSalarie");
                    _numSalarie = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("numSalarie");
                    OnnumSalarieChanged();
                }
            }
        }
        private global::System.Int32 _numSalarie;
        partial void OnnumSalarieChanging(global::System.Int32 value);
        partial void OnnumSalarieChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime dateIntervention
        {
            get
            {
                return _dateIntervention;
            }
            set
            {
                if (_dateIntervention != value)
                {
                    OndateInterventionChanging(value);
                    ReportPropertyChanging("dateIntervention");
                    _dateIntervention = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("dateIntervention");
                    OndateInterventionChanged();
                }
            }
        }
        private global::System.DateTime _dateIntervention;
        partial void OndateInterventionChanging(global::System.DateTime value);
        partial void OndateInterventionChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.TimeSpan heureDebut
        {
            get
            {
                return _heureDebut;
            }
            set
            {
                if (_heureDebut != value)
                {
                    OnheureDebutChanging(value);
                    ReportPropertyChanging("heureDebut");
                    _heureDebut = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("heureDebut");
                    OnheureDebutChanged();
                }
            }
        }
        private global::System.TimeSpan _heureDebut;
        partial void OnheureDebutChanging(global::System.TimeSpan value);
        partial void OnheureDebutChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> dureeIntervention
        {
            get
            {
                return _dureeIntervention;
            }
            set
            {
                OndureeInterventionChanging(value);
                ReportPropertyChanging("dureeIntervention");
                _dureeIntervention = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dureeIntervention");
                OndureeInterventionChanged();
            }
        }
        private Nullable<global::System.Int32> _dureeIntervention;
        partial void OndureeInterventionChanging(Nullable<global::System.Int32> value);
        partial void OndureeInterventionChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> nbKm
        {
            get
            {
                return _nbKm;
            }
            set
            {
                OnnbKmChanging(value);
                ReportPropertyChanging("nbKm");
                _nbKm = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("nbKm");
                OnnbKmChanged();
            }
        }
        private Nullable<global::System.Int32> _nbKm;
        partial void OnnbKmChanging(Nullable<global::System.Int32> value);
        partial void OnnbKmChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String numSS
        {
            get
            {
                return _numSS;
            }
            set
            {
                OnnumSSChanging(value);
                ReportPropertyChanging("numSS");
                _numSS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("numSS");
                OnnumSSChanged();
            }
        }
        private global::System.String _numSS;
        partial void OnnumSSChanging(global::System.String value);
        partial void OnnumSSChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> numVehicule
        {
            get
            {
                return _numVehicule;
            }
            set
            {
                OnnumVehiculeChanging(value);
                ReportPropertyChanging("numVehicule");
                _numVehicule = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("numVehicule");
                OnnumVehiculeChanged();
            }
        }
        private Nullable<global::System.Int32> _numVehicule;
        partial void OnnumVehiculeChanging(Nullable<global::System.Int32> value);
        partial void OnnumVehiculeChanged();

        #endregion
    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("asdomiModel", "FK_intervention_vehicule", "vehicule")]
        public vehicule vehicule
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<vehicule>("asdomiModel.FK_intervention_vehicule", "vehicule").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<vehicule>("asdomiModel.FK_intervention_vehicule", "vehicule").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<vehicule> vehiculeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<vehicule>("asdomiModel.FK_intervention_vehicule", "vehicule");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<vehicule>("asdomiModel.FK_intervention_vehicule", "vehicule", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="asdomiModel", Name="patient")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class patient : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet patient.
        /// </summary>
        /// <param name="numSS">Valeur initiale de la propriété numSS.</param>
        public static patient Createpatient(global::System.String numSS)
        {
            patient patient = new patient();
            patient.numSS = numSS;
            return patient;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String numSS
        {
            get
            {
                return _numSS;
            }
            set
            {
                if (_numSS != value)
                {
                    OnnumSSChanging(value);
                    ReportPropertyChanging("numSS");
                    _numSS = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("numSS");
                    OnnumSSChanged();
                }
            }
        }
        private global::System.String _numSS;
        partial void OnnumSSChanging(global::System.String value);
        partial void OnnumSSChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nomPatient
        {
            get
            {
                return _nomPatient;
            }
            set
            {
                OnnomPatientChanging(value);
                ReportPropertyChanging("nomPatient");
                _nomPatient = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nomPatient");
                OnnomPatientChanged();
            }
        }
        private global::System.String _nomPatient;
        partial void OnnomPatientChanging(global::System.String value);
        partial void OnnomPatientChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String prenomPatient
        {
            get
            {
                return _prenomPatient;
            }
            set
            {
                OnprenomPatientChanging(value);
                ReportPropertyChanging("prenomPatient");
                _prenomPatient = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("prenomPatient");
                OnprenomPatientChanged();
            }
        }
        private global::System.String _prenomPatient;
        partial void OnprenomPatientChanging(global::System.String value);
        partial void OnprenomPatientChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ruePatient
        {
            get
            {
                return _ruePatient;
            }
            set
            {
                OnruePatientChanging(value);
                ReportPropertyChanging("ruePatient");
                _ruePatient = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ruePatient");
                OnruePatientChanged();
            }
        }
        private global::System.String _ruePatient;
        partial void OnruePatientChanging(global::System.String value);
        partial void OnruePatientChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String villePatient
        {
            get
            {
                return _villePatient;
            }
            set
            {
                OnvillePatientChanging(value);
                ReportPropertyChanging("villePatient");
                _villePatient = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("villePatient");
                OnvillePatientChanged();
            }
        }
        private global::System.String _villePatient;
        partial void OnvillePatientChanging(global::System.String value);
        partial void OnvillePatientChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String cpPatient
        {
            get
            {
                return _cpPatient;
            }
            set
            {
                OncpPatientChanging(value);
                ReportPropertyChanging("cpPatient");
                _cpPatient = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("cpPatient");
                OncpPatientChanged();
            }
        }
        private global::System.String _cpPatient;
        partial void OncpPatientChanging(global::System.String value);
        partial void OncpPatientChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> datenaissPatient
        {
            get
            {
                return _datenaissPatient;
            }
            set
            {
                OndatenaissPatientChanging(value);
                ReportPropertyChanging("datenaissPatient");
                _datenaissPatient = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("datenaissPatient");
                OndatenaissPatientChanged();
            }
        }
        private Nullable<global::System.DateTime> _datenaissPatient;
        partial void OndatenaissPatientChanging(Nullable<global::System.DateTime> value);
        partial void OndatenaissPatientChanged();

        #endregion
    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("asdomiModel", "FK_intervention_patient", "intervention")]
        public EntityCollection<intervention> lesInterventions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<intervention>("asdomiModel.FK_intervention_patient", "intervention");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<intervention>("asdomiModel.FK_intervention_patient", "intervention", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="asdomiModel", Name="salarie")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class salarie : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet salarie.
        /// </summary>
        /// <param name="numSalarie">Valeur initiale de la propriété numSalarie.</param>
        public static salarie Createsalarie(global::System.Int32 numSalarie)
        {
            salarie salarie = new salarie();
            salarie.numSalarie = numSalarie;
            return salarie;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 numSalarie
        {
            get
            {
                return _numSalarie;
            }
            set
            {
                if (_numSalarie != value)
                {
                    OnnumSalarieChanging(value);
                    ReportPropertyChanging("numSalarie");
                    _numSalarie = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("numSalarie");
                    OnnumSalarieChanged();
                }
            }
        }
        private global::System.Int32 _numSalarie;
        partial void OnnumSalarieChanging(global::System.Int32 value);
        partial void OnnumSalarieChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nomSalarie
        {
            get
            {
                return _nomSalarie;
            }
            set
            {
                OnnomSalarieChanging(value);
                ReportPropertyChanging("nomSalarie");
                _nomSalarie = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nomSalarie");
                OnnomSalarieChanged();
            }
        }
        private global::System.String _nomSalarie;
        partial void OnnomSalarieChanging(global::System.String value);
        partial void OnnomSalarieChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String prenomSalarie
        {
            get
            {
                return _prenomSalarie;
            }
            set
            {
                OnprenomSalarieChanging(value);
                ReportPropertyChanging("prenomSalarie");
                _prenomSalarie = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("prenomSalarie");
                OnprenomSalarieChanged();
            }
        }
        private global::System.String _prenomSalarie;
        partial void OnprenomSalarieChanging(global::System.String value);
        partial void OnprenomSalarieChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String telSalarie
        {
            get
            {
                return _telSalarie;
            }
            set
            {
                OntelSalarieChanging(value);
                ReportPropertyChanging("telSalarie");
                _telSalarie = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("telSalarie");
                OntelSalarieChanged();
            }
        }
        private global::System.String _telSalarie;
        partial void OntelSalarieChanging(global::System.String value);
        partial void OntelSalarieChanged();

        #endregion
    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("asdomiModel", "FK_intervention_salarie", "intervention")]
        public EntityCollection<intervention> lesInterventions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<intervention>("asdomiModel.FK_intervention_salarie", "intervention");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<intervention>("asdomiModel.FK_intervention_salarie", "intervention", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="asdomiModel", Name="vehicule")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vehicule : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet vehicule.
        /// </summary>
        /// <param name="numVehicule">Valeur initiale de la propriété numVehicule.</param>
        public static vehicule Createvehicule(global::System.Int32 numVehicule)
        {
            vehicule vehicule = new vehicule();
            vehicule.numVehicule = numVehicule;
            return vehicule;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 numVehicule
        {
            get
            {
                return _numVehicule;
            }
            set
            {
                if (_numVehicule != value)
                {
                    OnnumVehiculeChanging(value);
                    ReportPropertyChanging("numVehicule");
                    _numVehicule = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("numVehicule");
                    OnnumVehiculeChanged();
                }
            }
        }
        private global::System.Int32 _numVehicule;
        partial void OnnumVehiculeChanging(global::System.Int32 value);
        partial void OnnumVehiculeChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String noImmat
        {
            get
            {
                return _noImmat;
            }
            set
            {
                OnnoImmatChanging(value);
                ReportPropertyChanging("noImmat");
                _noImmat = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("noImmat");
                OnnoImmatChanged();
            }
        }
        private global::System.String _noImmat;
        partial void OnnoImmatChanging(global::System.String value);
        partial void OnnoImmatChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String marque
        {
            get
            {
                return _marque;
            }
            set
            {
                OnmarqueChanging(value);
                ReportPropertyChanging("marque");
                _marque = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("marque");
                OnmarqueChanged();
            }
        }
        private global::System.String _marque;
        partial void OnmarqueChanging(global::System.String value);
        partial void OnmarqueChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String categorie
        {
            get
            {
                return _categorie;
            }
            set
            {
                OncategorieChanging(value);
                ReportPropertyChanging("categorie");
                _categorie = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("categorie");
                OncategorieChanged();
            }
        }
        private global::System.String _categorie;
        partial void OncategorieChanging(global::System.String value);
        partial void OncategorieChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> dateAcquisition
        {
            get
            {
                return _dateAcquisition;
            }
            set
            {
                OndateAcquisitionChanging(value);
                ReportPropertyChanging("dateAcquisition");
                _dateAcquisition = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dateAcquisition");
                OndateAcquisitionChanged();
            }
        }
        private Nullable<global::System.DateTime> _dateAcquisition;
        partial void OndateAcquisitionChanging(Nullable<global::System.DateTime> value);
        partial void OndateAcquisitionChanged();

        #endregion
    
    }

    #endregion
    
}
